stages:
  - test
  - build
  - deploy

variables:
  NODE_ENV: 'test'
  CI_NODE_VERSION: '20'

cache:
  paths:
    - node_modules/
    - .pnpm-store/

before_script:
  - node --version
  - npm --version
  - pnpm --version
  - pnpm install

test:
  stage: test
  script:
    - pnpm lint
    - pnpm test --coverage
    - pnpm build
  artifacts:
    paths:
      - coverage/
      - dist/
    when: always

build:
  stage: build
  script:
    - pnpm build:all
  artifacts:
    paths:
      - dist/
    expire_in: 1 week

deploy:
  stage: deploy
  script:
    - pnpm deploy
  only:
    - main
  environment:
    name: production
    url: https://fyndra.com
    on_stop: stop

stop:
  stage: deploy
  script:
    - pnpm deploy:stop
  when: manual
  environment:
    name: production
    action: stop
